package com.mycompany.audocao1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pcami
 */
public class CadastroEvento extends javax.swing.JFrame {

    /**
     * Creates new form CadastroEvento
     */
    public CadastroEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        descricaoField = new javax.swing.JTextField();
        datafinalField = new javax.swing.JTextField();
        datainicioField = new javax.swing.JTextField();
        criarEvento = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(490, 520));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 40)); // NOI18N
        jLabel1.setText("Cadastro de Eventos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 50, 480, 45);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 80, 20);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Descrição:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 200, 96, 20);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Data Inicial:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 290, 147, 20);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Data Final:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 350, 100, 20);

        nomeField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeField);
        nomeField.setBounds(30, 160, 270, 30);

        descricaoField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        descricaoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(descricaoField);
        descricaoField.setBounds(30, 230, 270, 30);

        datafinalField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        datafinalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datafinalFieldActionPerformed(evt);
            }
        });
        getContentPane().add(datafinalField);
        datafinalField.setBounds(30, 380, 140, 25);

        datainicioField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        getContentPane().add(datainicioField);
        datainicioField.setBounds(30, 320, 139, 25);

        criarEvento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        criarEvento.setText("Criar");
        criarEvento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        criarEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        criarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarEventoActionPerformed(evt);
            }
        });
        getContentPane().add(criarEvento);
        criarEvento.setBounds(30, 430, 84, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/OlhinhosC.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 490, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void descricaoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoFieldActionPerformed

    private void datafinalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datafinalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datafinalFieldActionPerformed

    private void criarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarEventoActionPerformed

    }//GEN-LAST:event_criarEventoActionPerformed

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarEvento;
    private javax.swing.JTextField datafinalField;
    private javax.swing.JTextField datainicioField;
    private javax.swing.JTextField descricaoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField nomeField;
    // End of variables declaration//GEN-END:variables
}
