/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.audocao1;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author pcami
 */
public class CadastroUsuarioTela extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuarioTela
     */
    public CadastroUsuarioTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        verificarsenhaField = new javax.swing.JPasswordField();
        senhaField = new javax.swing.JPasswordField();
        nomeField = new javax.swing.JTextField();
        idadeField = new javax.swing.JTextField();
        generoField = new javax.swing.JTextField();
        cpfField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(434, 620));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel1.setText("Criar Conta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 243, 66);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("NOME/USUÁRIO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 170, 23);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("IDADE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 170, 70, 23);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("GÊNERO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 240, 90, 23);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("EMAIL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 390, 70, 23);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("CPF");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 320, 50, 23);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("SENHA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 460, 60, 23);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setText("VERIFICAR SENHA");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(150, 460, 160, 23);
        getContentPane().add(verificarsenhaField);
        verificarsenhaField.setBounds(160, 490, 130, 30);

        senhaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaField);
        senhaField.setBounds(10, 490, 130, 30);

        nomeField.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeField);
        nomeField.setBounds(10, 130, 190, 30);

        idadeField.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        idadeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(idadeField);
        idadeField.setBounds(10, 200, 190, 30);

        generoField.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        generoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(generoField);
        generoField.setBounds(10, 270, 190, 30);

        cpfField.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        getContentPane().add(cpfField);
        cpfField.setBounds(10, 350, 190, 30);

        emailField.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField);
        emailField.setBounds(10, 420, 190, 30);

        cadastrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cadastrar.setText("OK");
        cadastrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(260, 550, 84, 25);

        jLabel7.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pegadasPa.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 430, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    private void idadeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idadeFieldActionPerformed

    private void generoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoFieldActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
         try {
            registerUser();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
         var JanelaA = new JanelaA();
                    JanelaA.setVisible(true);
                    dispose();
        

    }//GEN-LAST:event_cadastrarActionPerformed

    private void senhaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFieldActionPerformed
    
    private void registerUser() throws SQLException {
        String nome = nomeField.getText();
        String idade = idadeField.getText();
        String genero = generoField.getText();
        String cpf = cpfField.getText();
        String email = emailField.getText();
        String senha = new String(senhaField.getPassword());
        String verificarSenha = new String(verificarsenhaField.getPassword());

        if (!senha.equals(verificarSenha)) {
            JOptionPane.showMessageDialog(this, "Senhas não coincidem!");
            return;
        }

        Cadastro cadastro = new Cadastro();
        cadastro.setNome(nome);
        cadastro.setIdade(Integer.parseInt(idade));
        cadastro.setGenero(genero);
        cadastro.setCpf(cpf);
        cadastro.setEmail(email);
        cadastro.setSenha(senha);
        cadastro.setVerificarSenha(verificarSenha);

        CadastroDAO cadastroDAO = new CadastroDAO();
        cadastroDAO.cadastrar(cadastro);

        JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuarioTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField cpfField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField generoField;
    private javax.swing.JTextField idadeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeField;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JPasswordField verificarsenhaField;
    // End of variables declaration//GEN-END:variables
}
